config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root 'pages#home'
    # root rout sends this request to the pages controller
    # Then a home function within the application controller will get executed
    # So, should write some code in the pages controller file
    
    get '/about', to: 'pages#about'
    # get or grab "this route and send it to the pages controller's about action"
    
    get '/help', to: 'pages#help'
    
    resources :todos
    ## The above line gives all the CRUD routes for todos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    
    # we inherit from ApplicationRecord because Rails provides the model 
    # application_record for us
    validates :name, presence: true
    validates :description, presence: true
end
    # ActiveRecord::Base was used in Rails 4

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
    
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    # Actions are methods/functions in rails
    # NOTE: Because we have pages_controller file in the controllers folder,
    # We need to have a pages folder under views
    def home
        # There is no code here but by convention because there is a home action
        # Rails knows that there is a pages controller there is a pages folder under
        # Views that has a home file within it
    end
    
    def about
        
    end
    
    def help
        
    end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    # we can use a before filter
    # We don't want to do this for all of our methods
    ## only for show, edit, update and destroy
    # so add only keyword with square brackets and inside of it specify which
    # methods you want to apply it to
    ## So.. what this says is before we do anything for these methods run the
    # the set to do method which sets the todo by running the line of code inside of it
    before_action :set_todo, only: [:edit, :update, :show, :destroy]
    
    def new
        @todo = Todo.new
    end
    
    def create
        @todo = Todo.new(todo_params)
        if @todo.save 
            flash[:notice] = "Todo was creadted successfully!"
            # save to the database
            ## if it saves we want to redirect to a specific page
            redirect_to todo_path(@todo)
        else
            render 'new'
        end
    end
    
    def show
    end
    
    def edit
        # Grab the id from the param and find a todo to edit it
    end
    
    def index
        # grabs all todos from the database
        @todos = Todo.all
    end
    
    def destroy
        # first find the todo
        # Then call the destroy method
        @todo.destroy
        # once you destroy it give a flash notice
        flash[:notice] = "Todo was deleted successfully"
        redirect_to todos_path
    end
    
    def update
        # will look similar to the create action
        if @todo.update(todo_params)
            flash[:notice] = "Todo was successfully updated"
            redirect_to todo_path(@todo)
        else
            render 'edit'
        end
    end
    
    private 
    
    def set_todo
        @todo = Todo.find(params[:id])
    end
    
    def todo_params
        # Whitelist the name and description
        ## allowing what our application can receive 
        params.require(:todo).permit(:name, :description)
    end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<!-- Create a partial to make application.html.erb clean -->
<!-- need to render this in the application.html.erb file -->

 <% flash.each do |name, msg| %>
  <ul>
      <li><%= msg %></li>
  </ul>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render "layouts/messages" %>
      <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/help.html.erb
<h1>This is the help page</h1>

app/views/pages/home.html.erb
<h1>Hello world!</h1>

app/views/todos/_form.html.erb
<!-- fix clutter in edit and new files -->

<!--Checks to see if there are any errors-->
<% if @todo.errors.any? %>
    <h2>The following errors prevented the to do from being saved</h2>
    <ul>
        <% @todo.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <%end%>
    </ul>
<% end %>

<!--you need to add the = sign after the % to make embedded code appear on screen-->
<%= form_for @todo do |f| %>

    <p>
        <%= f.label :name %> <br>
        <%= f.text_field :name %>
    </p>
    
    <p>
        <%= f.label :description %> <br>
        <%= f.text_area :description %>
    </p>

    <p>
        <%= f.submit %>
        
    </p>

<% end %>

<%= link_to "Back to todos listing", todos_path %>

app/views/todos/edit.html.erb
<h1>Edit a Todo</h1>
 <!--Checks to see if there are any errors-->
<!-- we don't need to add the folder to the path name since _form is in the 
same folder as edit -->

<%= render "form" %>

app/views/todos/index.html.erb
<h1>Listing of todos</h1>

<p>
    <%= link_to "Create a Todo", new_todo_path %>
</p>

<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <% @todos.each do |todo| %>
        <tr>
            <td> <%= todo.name %> </td>
            <td> <%= todo.description %> </td>
            <!--Add an edit and show buttons to each todo-->
            <td> <%= link_to "Edit a todo", edit_todo_path(todo) %> </td>
            <td> <%= link_to "Show", todo_path(todo) %> </td>
            <!--add the destroy methid-->
            <!--need to specify it's a delete method-->
            <td> <%= link_to "Delete", todo_path(todo), method: :delete, data: {confirm: "Are you sure?"} %></td>
            <!--the date.. onwards is javascript code for confirming deletion-->
        </tr>
    <% end %>
</table>

app/views/todos/new.html.erb
<h1>Create a new todo</h1>
<%= render "form" %>

app/views/todos/show.html.erb
<h1>Showing a todo</h1>

<p>
    name: <%= @todo.name %>    
</p>
<p>
    <!--We get the @todo from our show action-->
    description: <%= @todo.description %>
</p>


<%= link_to "List of todos", todos_path %> |
<%= link_to "Edit this todo", edit_todo_path(@todo) %>



<!--
Hootsuite Co-op Software Developer


Hello Jessica,

I want to thank you once again for inviting me to the Interview on Thursday. It was a pleasure to meet you, George and Kush. After our discussion on this position and about Hootsuite, I would like to genuinely say that I am very excited about the prospect of joining Hootsuite as a Software Developer. If there are any additional steps or anything you require me to do, please do not hesitate to let me know.

I hope to hear from you soon.

Regards,


Kenan Abdulkarim
604-442-6525
-->